### ISSUE TITLE
Best Effort Meaning

### ISSUE THREAD

**Issue by jpviollet** [SMPTE/st429-20#17]
. The Table in ST 377:2004 section 3 defines Best Effort meaning as: **Encoder “should encode”; Decoder “shall decode”**

. Table 3 in ST 377-1:2019 section 4.4 defines Best Effort meaning as: **Encoder “shall encode”; Decoder “should decode”**

The meaning is reversed. It seems we need to adopt ST377:2004 Best Effort meaning – e.g., to process files in same way, and to be sure existing 2004 compliant files won’t suddenly be considered not compliant. It would indeed possibly avoid issue for the items that are flagged as Best Effort in both standards, for example:

- Frame Layout, Stored Width, Stored Height, Aspect Ratio, and Video Line Map items of the generic picture essence descriptor.
- Audio sampling rate, ChannelCount, Quantization bits of the generic sound essence descriptor
- etc…

And items that are Best Effort in only one standard, if any, would need to be addressed individually – Note: It seems Duration items in Sequence (picture/sound/data), SourceClip (picture/sound/data), Sequence (DM), DM Segment, and DM SourceClip end up being Best Effort in ST377-1:2019 in the same cases as in ST 377:2004 if I am not wrong.

**Comment by jpviollet** [comment]
I received confirmation that some D-Cinema encoders omit the **Duration** item in **Sequence (DM)** and **DM SourceClip** as well.

**Comment by palemieux** [comment]
> I received confirmation that some D-Cinema encoders omit the Duration item in Sequence (DM) and DM SourceClip as well.

@jpviollet Addressed at https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/EUUovPYqC79Pqb99jv48-mABM7057yAieR66pvQu3huRug?e=FUhtVR

**Comment by jpviollet** [comment]
The revised section 5.14 looks good to me, thank you - that being said, like done so far, we may want to keep this comment open until we decide to move document to next step in case additional properties end up identified.

**Comment by palemieux** [comment]
@jpviollet It is bad practice to keep issues opened indefinitely. A new issue can be open as needed.

**Comment by jpviollet** [comment]
I thought this is what was agreed so far - I was not requesting to keep it indefinitely, just until we decide to move to next step with draft. That being said, from Dolby implementations perspective, I am fine with closing this issue now. Thank you.

**Comment by palemieux** [comment]
Per 2022-02-10: closing as resolved by https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/EUUovPYqC79Pqb99jv48-mABM7057yAieR66pvQu3huRug?e=FUhtVR
