### ISSUE TITLE
Adjacent KLV Fill Items

### ISSUE THREAD

**Issue by jpviollet** [SMPTE/st429-20#25]
. ST429-3, section 4.3.10, allows KLV Fill items to be used in D-Cinema
. ST377:2004, section 5.3.3, states: “_KLV fill items **shall** not be placed adjacent to each other in a file. Any contiguous KLV fill items **shall** be concatenated into a single KLV fill Item_”.
. ST377-1:2019, section 6.3.3, states: “_KLV Fill items **should** not be placed adjacent to each other in a file. Any contiguous KLV Fill items **should** be concatenated into a single KLV Fill Item_.”

We checked our implementations, and they seem to support adjacent KLV Fill items. Assuming implementations from others do the same, it does NOT appear needed to reverse the requirement back to a “shall” statement. However, highlighting this difference feels beneficial to encourage encoders to avoid adjacent KLV Fill items - in case this could be a problem somewhere. Maybe something like:

**ST377:2004, 5.3.3, forbids adjacent KLV Fill items. ST377-1:2019, 6.3.3, allows them. At the time this specification is written, no implementation has been identified as having a problem with adjacent KLV Fill items, however, for strict compliance with ST377:2004 and to be safe it is recommended to avoid adjacent KLV Fill items – as stated in ST377-1:2019, any contiguous KLV Fill items should be concatenated into a single KLV Fill Item.**

Hope it makes sense. Thank you.

**Comment by palemieux** [comment]
Addressed at https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/EWOQce9c175Gqvj4HMxeC1wBS_whHu6XMwwt19Ch_zAerg?e=Gy9Zl1

**Comment by jpviollet** [comment]
The revised draft resolved my comment, thank you.
